[build]
  # 指定 Netlify 函数（serverless functions）的代码目录
  # 这里我们把函数代码放在项目根目录的 "api" 文件夹中
  functions = "api"

  # 指定静态文件发布目录
  # 这里将项目根目录下的 "public" 文件夹作为发布目录
  publish = "public"

# 重写规则配置
# 通过该规则，将所有以 /api/ 开头的请求，重写转发到 Netlify 函数的默认路径
# Netlify 函数默认暴露在 /.netlify/functions/ 目录下
[[redirects]]
  # 监听所有 /api/xxx 路径请求
  from = "/api/*"

  # 内部重写到对应的函数路径 /.netlify/functions/xxx
  # :splat 是通配符，代表匹配到的具体函数名或路径
  to = "/.netlify/functions/:splat"

  # 状态码 200 表示内部重写（Rewrite），不会改变浏览器地址栏的 URL
  status = 200
